In [34]:
import numpy as np
import pandas as pd
import metadpy
from metadpy import fit_meta_d_MLE

ImportError: cannot import name 'fit_meta_d_MLE' from 'metadpy' (/Users/zhengyuanrui/opt/anaconda3/lib/python3.8/site-packages/metadpy/__init__.py)

In [13]:
df_cnn = pd.read_csv("/Users/zhengyuanrui/CNN_Moral-MetaCog/result/reuslt_cnn.csv")

In [14]:
df = pd.read_csv("/Users/zhengyuanrui/CNN_Moral-MetaCog/data/sub/sub1_metad.csv")

In [19]:
def confidence_value(x):
    if x["rating"] == 2:
        return 1
    else:
        return 0

In [20]:
df["rating"] = df.apply(lambda x: confidence_value(x), axis=1)

In [21]:
df

,stimulus,trials_id,acc,correct_response,decision,rt,decision_2,stim,response,rating
0,../data/img/test/triangle/triangle12_4.png,1,1,Good,好人,1217,正确,1,1,1
1,../data/img/test/triangle/triangle26_3.png,2,1,Good,好人,1246,正确,1,1,1
2,../data/img/test/triangle/triangle82_3.png,3,1,Good,好人,1602,正确,1,1,1
3,../data/img/test/circle/circle34_4.png,4,1,No_info,无信息,1267,正确,0,0,1
4,../data/img/test/triangle/triangle63_1.png,6,0,Good,无信息,1258,错误,1,0,0
...,...,...,...,...,...,...,...,...,...,...
333,../data/img/test/triangle/triangle63_3.png,355,1,Good,好人,1418,正确,1,1,1
334,../data/img/test/square/square44_4.png,356,1,Bad,坏人,1428,错误,0,0,0
335,../data/img/test/circle/circle44_2.png,357,1,No_info,无信息,1549,正确,0,0,1
336,../data/img/test/circle/circle41_2.png,359,1,No_info,无信息,980,正确,0,0,1
337,../data/img/test/triangle/triangle11_5.png,360,1,Good,好人,1362,错误,1,1,0

In [22]:
df_cnn

     Unnamed: 0  response  stim  acc  confidence
0             0         0     0    1           1
1             1         0     0    0           1
2             2         0     0    1           1
3             3         0     0    1           1
4             4         0     0    0           0
..          ...       ...   ...  ...         ...
355         355         0     0    1           1
356         356         0     0    1           1
357         357         0     1    0           1
358         358         0     0    1           1
359         359         1     0    0           1

[360 rows x 5 columns]

In [31]:
CNN_nR_S1 = [49, 131, 14, 46]
CNN_nR_S2 = [24, 17, 14, 65]

In [36]:
metadpy.mle.metad(CNN_nR_S1, CNN_nR_S2)

ValueError: If using all scalar values, you must pass an index